CREATE TABLE chapter
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_chapter PRIMARY KEY (id)
);

CREATE TABLE checkpoint
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT                                    NOT NULL,
    question    TEXT                                    NOT NULL,
    image_data  TEXT                                    NOT NULL,
    chapter_id  BIGINT,
    CONSTRAINT pk_checkpoint PRIMARY KEY (id)
);

CREATE TABLE post
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post             TEXT                                    NOT NULL,
    posted_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id          BIGINT,
    checkpoint_id    BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    birth_date date                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE checkpoint
    ADD CONSTRAINT FK_CHECKPOINT_ON_CHAPTER FOREIGN KEY (chapter_id) REFERENCES chapter (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_CHECKPOINT FOREIGN KEY (checkpoint_id) REFERENCES checkpoint (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);